### PR TITLE
Update dev-server.js

### PR DESCRIPTION
**Pull request by huijiewei**
fix webpack-dev-server provide own certificate problem

### CODE REVIEW

**Comment by patricklafrance** [comment]
Hi @huijiewei 

What's your config?

With the following config, it works in my projects

```
    devServer: whenDev(() => ({
        https: true,
        pfx: fs.readFileSync(path.resolve("./devtools/https/localhost.pfx")),
        pfxPassphrase: "..."
    })),
```

**Comment by huijiewei** [comment]
https://webpack.js.org/configuration/dev-server/#devserver-https

```
devServer: {
    https: {
      key: fs.readFileSync('/path/to/server.key'),
      cert: fs.readFileSync('/path/to/server.crt'),
      ca: fs.readFileSync('/path/to/ca.pem'),
    }
  }
```

**Comment by patricklafrance** [comment]
Got it! thx

**Comment by patricklafrance** [comment]
Released as `3.2.2-alpha.0`

I will release to `latest` when I get back from vacation in a few days.

**Pull request merged**
