### PR TITLE
Added an example configuration file to set up the Less loader

### PR DESCRIPTION
**Pull request by ndbroadbent**
Based on https://github.com/sharegate/craco/issues/5#issuecomment-436468970

I added some error messages to cover all the cases where something might go wrong. Hopefully this will make it easier to update `create-react-app` and `craco` in the future.

### CODE REVIEW

**Comment by patricklafrance** [comment]
@ndbroadbent of course. Every decent plugins should be linked to in the documentation.

My first thought is to add the plugin section to the README of the [root repository](https://github.com/sharegate/craco/blob/master/README.md), what do you think?

**Comment by ndbroadbent** [comment]
Hi @patricklafrance, I've published a Less package on NPM called `craco-less`: 

* [craco-less on NPM](https://www.npmjs.com/package/craco-less)
* [craco-less on GitHub](https://github.com/ndbroadbent/craco-less)

I also published a plugin that sets up everything you need for [Ant Design](https://ant.design/) (it just wraps `craco-less`, and also adds `babel-plugin-import`.)

* [craco-antd on NPM](https://www.npmjs.com/package/craco-antd)
* [craco-antd on GitHub](https://github.com/ndbroadbent/craco-antd)

**Comment by ndbroadbent** [comment]
I was tempted to make one for Preact as well, but I think that would be silly. It's literally one line in my `craco.config.js`.

Here's my complete config now:

```
const CracoAntDesignPlugin = require('craco-antd');

module.exports = {
  webpack: { alias: { react: 'preact-compat', 'react-dom': 'preact-compat' } },
  plugins: [{ plugin: CracoAntDesignPlugin }],
};
```

This is so awesome!

**Comment by patricklafrance** [comment]
> I was tempted to make one for Preact as well, but I think that would be silly. It's literally one line in my `craco.config.js`.
> 
> Here's my complete config now:
> 
> ```
> const CracoAntDesignPlugin = require('craco-antd');
> 
> module.exports = {
>   webpack: { alias: { react: 'preact-compat', 'react-dom': 'preact-compat' } },
>   plugins: [{ plugin: CracoAntDesignPlugin }],
> };
> ```
> This is so awesome!

Good call, if someone need both, I am pretty sure they will figure out how to compose the pieces to make it work!

Thank you, this is awesome!

**Comment by patricklafrance** [comment]
@ndbroadbent Can you update your PR to use your plugin?

**Comment by ndbroadbent** [comment]
@patricklafrance Yes good idea, I've updated this to use the `craco-less` plugin instead

**Comment by patricklafrance** [comment]
@ndbroadbent Thanks!

**Pull request merged**
